---
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the packages in Redhat derivates
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ openssh_pkgs }}'

- name: Load ssh configuration
  template:
    src: sshd_config.{{ ansible_os_family }}.j2
    dest: /etc/ssh/sshd_config
    backup: yes
  notify: reload ssh

